### ISSUE TITLE
track_history doesn't work (see an error)

### ISSUE THREAD

**Issue by jakubstraka** [mongoid/mongoid-history#102]
Hello, I have a problem with setting up the gem. 

I'm making a Rails engine and want to have mongoid-history as part of it. But everytime I try to put track_history part into my model I got an error. In my model I have so far only one field.

In browser I see an error saying that the model itself doesn't work and see 'undefined method `each' for nil:NilClass' error.

In rails console I see this error

``` ruby
ArgumentError: wrong number of arguments (1 for 0)
    from /Users/Jakub/.rvm/gems/ruby-2.1.0@Motor/gems/activesupport-3.2.17/lib/active_support/core_ext/class/attribute_accessors.rb:40:in `touchable'
    from /Users/Jakub/.rvm/gems/ruby-2.1.0@Motor/gems/mongoid-3.1.6/lib/mongoid/relations/macros.rb:143:in `belongs_to'
    from /Users/Jakub/.rvm/gems/ruby-2.1.0@Motor/gems/mongoid-history-0.4.1/lib/mongoid/history/trackable.rb:36:in `track_history'
    from /Users/Jakub/Rails/Motor/app/models/motor/page.rb:33:in `<class:Page>'
    from /Users/Jakub/Rails/Motor/app/models/motor/page.rb:2:in `<module:Motor>'
    from /Users/Jakub/Rails/Motor/app/models/motor/page.rb:1:in `<top (required)>'
    from /Users/Jakub/.rvm/gems/ruby-2.1.0@Motor/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:469:in `load'
    from /Users/Jakub/.rvm/gems/ruby-2.1.0@Motor/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:469:in `block in load_file'
    from /Users/Jakub/.rvm/gems/ruby-2.1.0@Motor/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:639:in `new_constants_in'
    from /Users/Jakub/.rvm/gems/ruby-2.1.0@Motor/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:468:in `load_file'
    from /Users/Jakub/.rvm/gems/ruby-2.1.0@Motor/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:353:in `require_or_load'
    from /Users/Jakub/.rvm/gems/ruby-2.1.0@Motor/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:502:in `load_missing_constant'
    from /Users/Jakub/.rvm/gems/ruby-2.1.0@Motor/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:192:in `block in const_missing'
    from /Users/Jakub/.rvm/gems/ruby-2.1.0@Motor/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:190:in `each'
    from /Users/Jakub/.rvm/gems/ruby-2.1.0@Motor/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:190:in `const_missing'
    from (irb):1
    from /Users/Jakub/.rvm/gems/ruby-2.1.0@Motor/gems/railties-3.2.17/lib/rails/commands/console.rb:47:in `start'
    from /Users/Jakub/.rvm/gems/ruby-2.1.0@Motor/gems/railties-3.2.17/lib/rails/commands/console.rb:8:in `start'
    from /Users/Jakub/.rvm/gems/ruby-2.1.0@Motor/gems/railties-3.2.17/lib/rails/commands.rb:41:in `<top (required)>'
    from script/rails:6:in `require'
```

Note: I use Ruby 1.9.3 & Rails 3.2.17

Thanks for any help.
Jakub

**Comment by dblock** [comment]
This is old, closing. Please reopen if you can reproduce.
